version: '3.7'

services:
  client:
    env_file: ./deploy/.env_prod
    build:
      context: ./packages/ecp-app
      dockerfile: Dockerfile
      args:
        - VUE_APP_NAME=${VUE_APP_NAME}
        - VUE_APP_DOMAIN=${VUE_APP_DOMAIN}
        - VUE_APP_SERVER_URL=${VUE_APP_SERVER_URL}
        - VUE_APP_BROKER_URL=${VUE_APP_BROKER_URL}
        - VUE_APP_CLIENT_URL=${VUE_APP_CLIENT_URL}
        - VUE_APP_API_URL=${VUE_APP_API_URL}
        - VUE_APP_LOGGER_LEVEL=${VUE_APP_LOGGER_LEVEL}
    image: billxiong/ecp-app
    container_name: ecp-app

  client-server:
    env_file: ./deploy/.env_prod
    environment:
      - NGINX_HTTP_SERVER_PORT=${NGINX_HTTP_SERVER_PORT}
    build:
      context: ./packages/nginx
      dockerfile: Dockerfile
    restart: always
    container_name: ecp-nginx
    depends_on:
      - client
    ports:
      - '${NGINX_HTTP_SERVER_PORT}:80'
