version: '3.7'

services:
  client:
    env_file: ./deploy/.env_dev
    build:
      context: ./packages/ecp-app
      dockerfile: Dockerfile
      args:
        - VUE_APP_NAME=${VUE_APP_NAME}
        - VUE_APP_DOMAIN=${VUE_APP_DOMAIN}
        - VUE_APP_SERVER_URL=${VUE_APP_SERVER_URL}
        - VUE_APP_BROKER_URL=${VUE_APP_BROKER_URL}
        - VUE_APP_CLIENT_URL=${VUE_APP_CLIENT_URL}
        - VUE_APP_API_URL=${VUE_APP_API_URL}
        - VUE_APP_LOGGER_LEVEL=${VUE_APP_LOGGER_LEVEL}
    image: billxiong/ecp-app
    container_name: ecp-app
    volumes:
      - ./deploy/.env_dev:/home/node/ecp-app/.env:ro

  api:
    env_file: ./deploy/.env_dev
    build:
      context: ./packages/ecp-api
      dockerfile: Dockerfile
      args:
        - API_SERVER_PORT=${API_SERVER_PORT}
    ports:
      - '3033:3033'
    image: billxiong/ecp-api
    container_name: ecp-api
    volumes:
      - ./deploy/.env_dev:/home/node/ecp-api/.env:ro
    command: yarn run start

  client-server:
    environment:
      - NGINX_HTTP_SERVER_PORT=${NGINX_HTTP_SERVER_PORT}
    build:
      context: ./packages/nginx
      dockerfile: Dockerfile
    restart: always
    container_name: ecp-nginx
    volumes:
      - ./packages/nginx/nginx-local.template:/etc/nginx/nginx.template
    depends_on:
      - client
      - api
    ports:
      - '${NGINX_HTTP_SERVER_PORT}:80'
    expose:
      - 80
    network_mode: 'host'
    command: /bin/bash -c "envsubst < /etc/nginx/nginx.template > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"
